### PR TITLE
Use sortablejs to replace ./Sortable

### LINKED ISSUE #11: Webpack not resolving Sortable.js correctly
I'm learning webpack, so hopefully I'm not doing something stupid --

Shouldn't this project require Sortable as `sortablejs` instead of `./Sortable`, since it's no longer in the main Sortable repository?

If so, I can make a PR. :)

Thanks for the hard work.

### PR DESCRIPTION
**Pull request by doxiaodong**
fix https://github.com/SortableJS/angular-legacy-sortablejs/issues/11

### CODE REVIEW

**Comment by samjacobclift** [comment]
why do this change what does it fix?

**Comment by samjacobclift** [comment]
ahh just looked at the issue

**Comment by samjacobclift** [comment]
have you tried out the changes with webpack?

**Comment by doxiaodong** [comment]
Yep, but you need to check if it's necessary to add `sortablejs` into `peerDependencies`

**Comment by doxiaodong** [comment]
npm publish? @samjacobclift

**Pull request merged**
